--t?ng t? ??ng cho m?i hóa ??n ???c thêm vào
CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE_FOR_HOADON
START WITH 1
INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER AUTO_INCREMENT_TRIGGER_FOR_HODON
BEFORE INSERT ON HOADON REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
    SELECT AUTO_INCREMENT_SEQUENCE_FOR_HOADON.NEXTVAL INTO :NEW.SOHD
    FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER AUTO_INSERT_DATE_ON_HOADON
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    :NEW.NGHD := SYSDATE;
END;
/
alter session set nls_date_format = 'dd/MM/yyyy hh24:mi:ss'
/
--TRIGGER T? ??NG C?P NH?T TR? GIÁ SAU KHI GI?M GIÁ
CREATE OR REPLACE TRIGGER TRIGIA_TRGG
BEFORE INSERT OR UPDATE ON HOADON
FOR EACH ROW
BEGIN
    :NEW.TONGCONG := :NEW.TRIGIA - :NEW.GIAMGIA;
END;
/
CREATE OR REPLACE TRIGGER trigger_check_ngaytra_gia
BEFORE INSERT OR UPDATE ON GUITHUCUNG
FOR EACH ROW
DECLARE
    ngay_gui DATE;
    ngay_tra DATE;
BEGIN
    -- L?y giá tr? c?a c?t NGAYGUI và NGAYTRA
    ngay_gui := :NEW.NGAYGUI;
    ngay_tra := :NEW.NGAYTRA;

    -- N?u NGAYTRA là NULL, gán giá tr? m?c ??nh là NGAYGUI + 1 ngày
    IF ngay_tra IS NULL THEN
        ngay_tra := ngay_gui + INTERVAL '1' DAY;
    END IF;

    -- Ki?m tra n?u NGAYTRA không sau ho?c b?ng NGAYGUI ít nh?t 1 ngày, gán NGAYTRA = NGAYGUI + 1 ngày
    IF ngay_tra < ngay_gui + INTERVAL '1' DAY THEN
        ngay_tra := ngay_gui + INTERVAL '1' DAY;
    END IF;

    -- C?p nh?t giá tr? m?i cho c?t NGAYTRA
    :NEW.NGAYTRA := ngay_tra;

    -- Tính giá tr? cho c?t GIA
    :NEW.GIA := 200000 * (ngay_tra - ngay_gui);
END;
/
CREATE OR REPLACE TRIGGER AUTO_INSERT_DATE_FOR_GUITHUCUNG
BEFORE INSERT ON GUITHUCUNG
FOR EACH ROW
BEGIN
    :NEW.NGAYGUI := SYSDATE;
END;
/

CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE_FOR_guithucung
START WITH 1
INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER AUTO_INCREMENT_TRIGGER_FOR_guithucung
BEFORE INSERT ON GUITHUCUNG REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
    SELECT AUTO_INCREMENT_SEQUENCE_FOR_guithucung.NEXTVAL INTO :NEW.SOPHIEUGUI
    FROM DUAL;
END;
/

set serveroutput on
/
---b?t ??u ? ?ây
CREATE OR REPLACE TRIGGER HOADON_DEFAULT_TRIGIA
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    IF :NEW.TRIGIA IS NULL THEN
        :NEW.TRIGIA := 0;
    END IF;
END;
/

--r?i t?i ?ây
CREATE OR REPLACE PROCEDURE CAPNHAT_TRIGIA_HOADON (
    p_SOHD IN HOADON.SOHD%TYPE,
    p_TRIGIA IN HOADON.TRIGIA%TYPE
)
AS
BEGIN
    UPDATE HOADON
    SET TRIGIA = TRIGIA + p_TRIGIA
    WHERE SOHD = p_SOHD;
    
    COMMIT;
END;
/

CREATE OR REPLACE TRIGGER AUTOGIAM_SL_DANHMUC_TINHTHANHTIEN_TRIGIAHD
BEFORE INSERT ON CTHD
FOR EACH ROW
DECLARE
    SLSPBD DANHMUC.SL%TYPE; 
    GIA_MADM DANHMUC.GIA%TYPE; 
    TG HOADON.TRIGIA%TYPE;
    
BEGIN
    SELECT SL, GIA INTO SLSPBD, GIA_MADM FROM DANHMUC WHERE :NEW.ID = DANHMUC.MADM; 
    SELECT TRIGIA INTO TG FROM HOADON WHERE HOADON.SOHD = :NEW.SOHD;
    IF SLSPBD - :NEW.SL >= 0 THEN
    UPDATE DANHMUC SET SL = SLSPBD - :NEW.SL WHERE :NEW.ID = DANHMUC.MADM;  
    ELSE RAISE_APPLICATION_ERROR(-20000, 'So luong san pham chi con: ' || SLSPBD);
    END IF;
    :NEW.THANHTIEN := :NEW.SL * GIA_MADM;
    UPDATE HOADON SET TRIGIA = TG + :NEW.THANHTIEN WHERE :NEW.SOHD = HOADON.SOHD;
END;
/
